#ifndef SERVERWINAMPPLUGIN_GLOBAL_H
#define SERVERWINAMPPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SERVERWINAMPPLUGIN_LIBRARY)
#  define SERVERWINAMPPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SERVERWINAMPPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SERVERWINAMPPLUGIN_GLOBAL_H
