#ifndef PLUGIN_WINAMP_GLOBAL_H
#define PLUGIN_WINAMP_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PLUGIN_WINAMP_LIBRARY)
#  define PLUGIN_WINAMPSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PLUGIN_WINAMPSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGIN_WINAMP_GLOBAL_H
